core/urls.py
from django.urls import path
from core import views


app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("event/<str:eid>/", views.event_detail_view, name="event_detail"),
    path('search/', views.search_view, name='search'),
    path('cart/', views.cart_view, name='cart'),
    path('api/events/<str:eid>/', views.event_api, name='event_api'),
    path('payment/', views.payment_view, name='payment'),
    path('payment/success/', views.payment_success_view, name='payment_success'),
    path('api/check-auth/', views.check_auth, name='check_auth'),
    path('api/save-cart/', views.save_cart, name='save_cart'),
    path('process_payment/', views.process_payment, name='process_payment'),
]

eventbookingweb/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('user/', include("userauth.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauth/urls.py
from django.urls import path
from userauth import views

app_name = "userauth"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("login/", views.login_view, name="login"),
    path("login/<str:next>/", views.login_view, name="login-next"),
    path("logout/", views.logout_view, name="logout"),
    path("my-account/", views.user_profile, name="my-account"),
    path("edit-info/", views.edit_profile, name="edit-info"),
    path("change-password/", views.change_password, name='change-password')
]

templates/partials/base.html
{% load static %}

<!DOCTYPE html>
<html lang="vi">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/remixicon@4.0.0/fonts/remixicon.css" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}"/>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/images/logo_icon.png' %}">
    <title>Kết nối đam mê, sống trọn sự kiện | Eventick</title>
  </head>
  <body>
    <header class="header">
      <nav>
        <div class="nav__bar">
          <div class="logo">
            <a href="{% if request.path == '/' %}#home{% else %}{% url 'core:index' %}#{% endif %}"><img src="{% static 'assets/images/logo.png' %}" alt="logo" /></a>
          </div>
          <div class="nav__menu__btn" id="menu-btn">
            <i class="ri-menu-line"></i>
          </div>
        </div>
        <ul class="nav__links" id="nav-links">
          <li>
            <a href="{% if request.path == '/' %}#home{% else %}{% url 'core:index' %}#home{% endif %}">Trang Chủ</a>
          </li>
          <li>
            <a href="{% if request.path == '/' %}#event{% else %}{% url 'core:index' %}#event{% endif %}">Sự Kiện</a>
          </li>
          <li>
            <a href="{% if request.path == '/' %}#contact{% else %}{% url 'core:index' %}#contact{% endif %}">Liên Hệ</a>
          </li>
        </ul>
        <div class="nav__icons">
          {% if user.is_authenticated %}
          <span><i class="ri-coupon-line" style="color: white;"></i></span>
          {% endif %}
          <span class="cart-icon" onclick="window.location.href='{% url 'core:cart' %}'">
            <i class="ri-shopping-cart-line" style="color: white;"></i>
            <span class="cart-counter">0</span>
          </span>
            {% if user.is_authenticated %}
            <span class="user-icon" onclick="toggleDropdown()">
              <i class="ri-user-line" style="color: white;"></i>
            </span>
            <div id="user-dropdown" class="user-dropdown">
                <a href="{% url 'userauth:my-account' %}">Tài khoản</a>
                <form action="{% url 'userauth:logout' %}" method="POST">
                    {% csrf_token %}
                    <button type="submit">Đăng xuất</button>
                </form>
            </div>
            {% else %}
              <button class="nav__btn" onclick="window.location.href='{% url 'userauth:sign-up' %}'">Đăng Nhập</button>
            {% endif %}
        </div>  
        
      </nav>
    {% block header_content %}
    {% endblock header_content %}  
    </header>
    <!--End Header-->

    {% block content %}

    {% endblock content %}

    <!--Footer-->
    <footer class="footer" id="contact">
        <div class="section__container footer__container">
          <div class="footer__col">
            <div class="logo">
              <a href="{% if request.path == '/' %}#home{% else %}{% url 'core:index' %}#home{% endif %}"><img src="{% static 'assets/images/logo.png' %}" alt="logo" /></a>
            </div>
            <p class="section__description">
              Khám phá sự kiện thú vị quanh bạn! 
              Tìm kiếm, đặt vé ngay để trải nghiệm những trải nghiệm khó quên.
            </p>
          </div>
        
          <div class="footer__col">
            <h4>CONTACT US</h4>
            <ul class="footer__links">
              <li><a href="#">thaole@gmail.com</a></li>
            </ul>
            <div class="footer__socials">
              <a href="#"><img src="{% static 'assets/images/facebook.png' %}" alt="facebook" /></a>
              <a href="#"><img src="{% static 'assets/images/instagram.png' %}" alt="instagram" /></a>
              <a href="#"><img src="{% static 'assets/images/youtube.png' %}" alt="youtube" /></a>
              <a href="#"><img src="{% static 'assets/images/twitter.png' %}" alt="twitter" /></a>
            </div>
          </div>
        </div>
        <div class="footer__bar">
          Copyright © Le Thi Thu Thao. All rights reserved.
        </div>
      </footer>
  
      <script src="https://unpkg.com/scrollreveal"></script>
      <script src="{% static 'assets/js/main.js' %}"></script>
      <script src="{% static 'assets/js/cart.js' %}"></script>
  </body>
</html>