core/urls.py
from django.urls import path
from core import views


app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("event/<str:eid>/", views.event_detail_view, name="event_detail"),
    path('search/', views.search_view, name='search'),
    path('cart/', views.cart_view, name='cart'),
    path('api/events/<str:eid>/', views.event_api, name='event_api'),
    path('payment/', views.payment_view, name='payment'),
    path('payment/success/', views.payment_success_view, name='payment_success'),
    path('api/check-auth/', views.check_auth, name='check_auth'),
    path('api/save-cart/', views.save_cart, name='save_cart'),
    path('process_payment/', views.process_payment, name='process_payment'),
]

eventbookingweb/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('user/', include("userauth.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauth/urls.py
from django.urls import path
from userauth import views

app_name = "userauth"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("login/", views.login_view, name="login"),
    path("login/<str:next>/", views.login_view, name="login-next"),
    path("logout/", views.logout_view, name="logout"),
    path("my-account/", views.user_profile, name="my-account"),
    path("edit-info/", views.edit_profile, name="edit-info"),
    path("change-password/", views.change_password, name='change-password')
]

userauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import EmailValidator

class User(AbstractUser):
    email = models.EmailField(
        unique=True,
        null=False,
        validators=[EmailValidator(message="Please provide a valid email address.")],
    )
    username = models.CharField(
        max_length=100,
        unique=True,
        null=False,
        help_text="Required. 100 characters or fewer. Letters, digits, and @/./+/-/_ only.",
    )

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    def __str__(self):
        return self.username

userauth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from userauth.models import User

class UserRegisterForm(UserCreationForm):

    firstname = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ''}))
    lastname = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ''}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ''}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': ''}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': ''}))
    print(forms.CharField)
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': ''}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'firstname']

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ''}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': ''}))

userauth/views.py
from django.shortcuts import redirect, render
from userauth.forms import UserRegisterForm, UserLoginForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

import logging

logger = logging.getLogger(__name__)

def register_view(request):
    if request.method == "POST":
        form = UserRegisterForm(data = request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            username = form.cleaned_data.get('username')
            new_user.first_name = form.cleaned_data['firstname']
            new_user.last_name = form.cleaned_data['lastname']
            new_user.save()

            messages.success(request, f"Tạo tài khoản thành công cho {username}!")
            
            new_user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password1'],
                                    )
            
            login(request, new_user)
            return redirect('core:index')

    else:   
        form = UserRegisterForm()

    context = {
        'register_form': form,
        'login_form': UserLoginForm(),
    }
    return render(request, 'userauth/auth.html', context)

def login_view(request):
    if request.method == 'POST':
        form = UserLoginForm(data = request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                next_url = request.GET.get('next')
                if next_url:
                    return redirect(next_url)
                return redirect('core:index')
    else:
        form = UserLoginForm()

    context = {
        'register_form': form,
        'login_form': UserLoginForm(),
    }
    return render(request, 'userauth/auth.html', context)

def logout_view(request):
    logout(request)
    return redirect('core:index')

@login_required
def user_profile(request):
    user = request.user  
    context = {
        'username': user.username,
        'email': user.email,
        'first_name': user.first_name,
        'last_name': user.last_name,
    }
    return render(request, 'userauth/user_profile.html', context)

def edit_profile(request):
    if request.method == "POST":
        user = request.user
        user.username = request.POST.get('username')
        user.email = request.POST.get('email')
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        
        try:
            user.save()
            messages.success(request, "Cập nhật thông tin thành công!")
        except Exception as e:
            messages.error(request, "Có lỗi xảy ra khi cập nhật thông tin.")
            render(request, 'userauth/user_profile.html', {'user': request.user, 'error-message': 'Có lỗi xảy ra khi cập nhật thông tin.'})
        
    return render(request, 'userauth/user_profile.html', {'user': request.user})

def change_password(request):
    if request.method == "POST":
        current_password = request.POST.get('current_password')
        new_password = request.POST.get('new_password')
        confirm_password = request.POST.get('confirm_password')

        user = request.user
        
        if not user.check_password(current_password):
            messages.error(request, "Mật khẩu hiện tại không đúng!")
            return render(request, 'userauth/user_profile.html', {'message_status': 'Mật khẩu hiện tại không đúng!'})
            
        if new_password != confirm_password:
            messages.error(request, "Mật khẩu mới không khớp!")
            return render(request, 'userauth/user_profile.html', {'message_status': 'Mật khẩu mới không khớp!'})
            
        user.set_password(new_password)
        user.save()
        
        messages.success(request, "Đổi mật khẩu thành công!")
        login(request, user)
        
        return redirect('userauth:my-account')

templates/userauth/auth.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'assets/css/auth.css' %}"/>

      <div class="content">
        <div class="tabs">
          <button class="tab__btn active" data-tab="1">Đăng Nhập</button>
          <span></span>
          <button class="tab__btn" data-tab="2">Đăng Ký</button>
        </div>
        <div class="tabs__panel">
          
          <!--Login-->
          <div class="panel active" data-panel="1">
            <form method="POST" action="{% if request.GET.next %}{% url 'userauth:login' %}?next={{ request.GET.next }}{% else %}{% url 'userauth:login' %}{% endif %}">>
              {% csrf_token %}

              <div class="input__group__form">
                {{ login_form.username }}
                <label for="username">Tên Người Dùng</label>
              </div>
              <div class="input__group__form">
                {{ login_form.password }}
                <label for="login-password">Mật Khẩu</label>
                <span id="login-password-eye">
                  <i class="ri-eye-off-fill"></i>
                </span>
              </div>
              <button>Đăng Nhập</button>
            </form>
          </div>

          <!--Sign up-->
          <div class="panel" data-panel="2">
            <form method="POST" action="{% url 'userauth:sign-up' %}">
              {% csrf_token %}

              <div class="input__group__form">
                {{ register_form.firstname }}
                <label for="firstname">Tên</label>
              </div>
              <div class="input__group__form">
                {{ register_form.lastname }}
                <label for="lastname">Họ</label>
              </div>
              <div class="input__group__form">
                {{ register_form.username }}
                <label for="username">Tên Người Dùng</label>
              </div>
              <div class="input__group__form">
                {{ register_form.email }}
                <label for="email">Email</label>
              </div>
              <div class="input__group__form">
                {{ register_form.password1 }}
                <label for="signup-password">Mật Khẩu</label>
                <span id="signup-password-eye">
                  <i class="ri-eye-off-fill"></i>
                </span>
              </div>
              <div class="input__group__form">
                {{ register_form.password2 }}
                <label for="confirm-password">Xác Nhận Mật Khẩu</label>
                <span id="confirm-password-eye">
                  <i class="ri-eye-off-fill"></i>
                </span>
              </div>
              <button>Đăng Ký</button>
              <p>hoặc</p>
              <a href="">Đã có tài khoản? <span>Đăng nhập ngay!</span></a>
            </form>
          </div>
        </div>
      </div>

    <script src="{% static 'assets/js/auth.js' %}"></script>

{% endblock content %}

templates/userauth/user_profile.html
{% extends 'partials/base.html' %}
{% load static %}
{% load humanize %}

{% block header_content %}
<style>
    .header {
      background-color: var(--text-dark);
      background-position: center top;
      background-size: cover; 
      background-repeat: no-repeat;
      height: 10%;
    }
  </style>
{% endblock header_content %}

{% block content %}
<link rel="stylesheet" href="{% static 'assets/css/payment.css' %}"/>

<section class="section__container payment__container">
    {% if message_status %}
        <div id="error-message" class="error-message">{{ message_status }}</div>
    {% endif %}
    <h1 class="payment__title" style="color: #bc1c5c;"><strong>Quản lý tài khoản</strong></h1>
    <div>
        <button class="tab-btn active" data-tab="1">Thông tin cá nhân</button>
        <span></span>
        <button class="tab-btn" data-tab="2">Đổi mật khẩu</button>
    </div>
    
    <div class="panel active">
        <form id="paymentForm" method="POST" action="{% url 'userauth:edit-info' %}">
            {% csrf_token %}
            <div class="form__group">
                <label for="username">Tên tài khoản</label>
                <input type="text" id="username" name="username" value="{{ user.username }}">
            </div>
            <div class="form__group">
                <label for="email">Email</label>
                <input type="text" id="email" name="email" value="{{ user.email }}">
            </div>
            <div class="form__row">
                <div class="form__group">
                    <label for="last_name">Họ</label>
                    <input type="text" id="last_name" name="last_name" value="{{ user.last_name }}">
                </div>
                <div class="form__group">
                    <label for="first_name">Tên</label>
                    <input type="text" id="first_name" name="first_name" value="{{ user.first_name }}">
                </div>
            </div>
            <button type="submit" class="btn">Cập nhật thông tin</button>
        </form>
    </div>

    <div class="panel" >
        <form method="POST" action="{% url 'userauth:change-password' %}">
            {% csrf_token %}
            <div class="form__group">
                <label for="current_password">Mật khẩu hiện tại</label>
                <input type="password" id="current_password" name="current_password" required>
            </div>
            <div class="form__group">
                <label for="new_password">Mật khẩu mới</label>
                <input type="password" id="new_password" name="new_password" required>
            </div>
            <div class="form__group">
                <label for="confirm_password">Xác nhận mật khẩu</label>
                <input type="password" id="confirm_password" name="confirm_password" required>
            </div>
            <button type="submit" class="btn">Đổi mật khẩu</button>
        </form>
    </div>
</section>
<script src="{% static 'assets/js/user.js' %}"></script>
{% endblock content %}